# Form implementation generated from reading ui file 'GRS_about_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GRS_about_page(object):
    def setupUi(self, GRS_about_page):
        GRS_about_page.setObjectName("GRS_about_page")
        GRS_about_page.setFixedSize(361, 308)
        GRS_about_page.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Germany))
        GRS_about_page.setWindowIcon(QtGui.QIcon("resources/img/window_icons/GRS_mainWindow_icon.png"))
        self.AP_title1 = QtWidgets.QLabel(parent=GRS_about_page)
        self.AP_title1.setGeometry(QtCore.QRect(20, 10, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AP_title1.setFont(font)
        self.AP_title1.setObjectName("AP_title1")
        self.AP_title2 = QtWidgets.QLabel(parent=GRS_about_page)
        self.AP_title2.setGeometry(QtCore.QRect(10, 50, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.AP_title2.setFont(font)
        self.AP_title2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.AP_title2.setObjectName("AP_title2")
        self.AP_author_label = QtWidgets.QLabel(parent=GRS_about_page)
        self.AP_author_label.setGeometry(QtCore.QRect(140, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AP_author_label.setFont(font)
        self.AP_author_label.setObjectName("AP_author_label")
        self.AP_author_value = QtWidgets.QLabel(parent=GRS_about_page)
        self.AP_author_value.setGeometry(QtCore.QRect(120, 150, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AP_author_value.setFont(font)
        self.AP_author_value.setObjectName("AP_author_value")
        self.AP_author_value.setOpenExternalLinks(True)
        # Change for personal page link
        self.AP_author_value.setText('<a href="https://github.com/">Bruno Guiomar</a>')
        self.AP_repo_link = QtWidgets.QLabel(parent=GRS_about_page)
        self.AP_repo_link.setGeometry(QtCore.QRect(120, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AP_repo_link.setFont(font)
        self.AP_repo_link.setObjectName("AP_repo_link")
        self.AP_repo_link.setOpenExternalLinks(True)
        # Change for project repository link
        self.AP_repo_link.setText('<a href="https://github.com/">Repository</a>')
        self.AP_repo_link.setStyleSheet("color: rgb(51, 102, 204)")
        self.AP_dataset_link = QtWidgets.QLabel(parent=GRS_about_page)
        self.AP_dataset_link.setGeometry(QtCore.QRect(140, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AP_dataset_link.setFont(font)
        self.AP_dataset_link.setObjectName("AP_dataset_link")
        self.AP_dataset_link.setOpenExternalLinks(True)
        self.AP_dataset_link.setText('<a href="https://universe.roboflow.com/haw-hamburg-g6n2v/german-railway-signalling">Dataset</a>')
        self.AP_dataset_link.setStyleSheet("color: rgb(51, 102, 204)")

        self.retranslateUi(GRS_about_page)
        QtCore.QMetaObject.connectSlotsByName(GRS_about_page)

    def retranslateUi(self, GRS_about_page):
        _translate = QtCore.QCoreApplication.translate
        GRS_about_page.setWindowTitle(_translate("GRS_about_page", "Form"))
        self.AP_title1.setText(_translate("GRS_about_page", "German Railway Signalling"))
        self.AP_title2.setText(_translate("GRS_about_page", "Real-Time Object Detection"))
        self.AP_author_label.setText(_translate("GRS_about_page", "Author"))