from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGroupBox, QVBoxLayout

from utils.file_operations import get_model_metrics


class Ui_model_info_win(object):
    def setupUi(self, model_info_win, model_name):
        self.model_name = model_name
        self.model_path = "../models/" + self.model_name + "/model_info/"
        self.model_metrics = get_model_metrics(self.model_path)
        print(self.model_metrics)

        model_info_win.setObjectName("model_info_win")
        model_info_win.resize(1200, 711)
        model_info_win.setWindowTitle(model_name + " Information")
        self.menu = QtWidgets.QTabWidget(parent=model_info_win)
        self.menu.setGeometry(QtCore.QRect(0, 0, 1191, 711))
        self.menu.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Germany))
        model_info_win.setWindowIcon(QtGui.QIcon("resources/img/window_icons/GRS_mainWindow_icon.png"))
        self.menu.setObjectName("menu")

        self.overview_tab = QtWidgets.QWidget()
        self.overview_tab.setObjectName("overview_tab")
        self.overview_info_group = QGroupBox(parent=self.overview_tab)
        self.overview_info_group.setGeometry(QtCore.QRect(20, 20, 250, 250))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.overview_info_group.setFont(font)
        self.overview_info_group.setTitle("Model Specifications")
        self.overview_info_group_layout = QVBoxLayout()
        self.overview_info_group.setLayout(self.overview_info_group_layout)

        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.overview_model_name = QtWidgets.QLabel(parent=self.overview_info_group)
        self.overview_model_name.setFont(font)
        self.overview_model_name.setText("Model Name: " + self.model_name)
        self.overview_train_epochs = QtWidgets.QLabel(parent=self.overview_info_group)
        self.overview_train_epochs.setFont(font)
        self.overview_train_epochs.setText("Train Epochs: " + self.model_metrics["train_epochs"])
        self.overview_train_img_size = QtWidgets.QLabel(parent=self.overview_info_group)
        self.overview_train_img_size.setFont(font)
        self.overview_train_img_size.setText("Train IMG Size: " + self.model_metrics["train_IMG_size"])
        self.overview_precision = QtWidgets.QLabel(parent=self.overview_info_group)
        self.overview_precision.setFont(font)
        self.overview_precision.setText("Precision: " + self.model_metrics["precision"])
        self.overview_recall = QtWidgets.QLabel(parent=self.overview_info_group)
        self.overview_recall.setFont(font)
        self.overview_recall.setText("Recall: " + self.model_metrics["recall"])
        self.overview_mAP = QtWidgets.QLabel(parent=self.overview_info_group)
        self.overview_mAP.setFont(font)
        self.overview_mAP.setText("mAP: " + self.model_metrics["mAP"])

        self.overview_info_group_layout.addWidget(self.overview_model_name)
        self.overview_info_group_layout.addWidget(self.overview_train_epochs)
        self.overview_info_group_layout.addWidget(self.overview_train_img_size)
        self.overview_info_group_layout.addWidget(self.overview_precision)
        self.overview_info_group_layout.addWidget(self.overview_recall)
        self.overview_info_group_layout.addWidget(self.overview_mAP)
        self.menu.addTab(self.overview_tab, "Overview")

        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.train_img = QtWidgets.QLabel(parent=self.train_tab)
        self.train_img.setGeometry(QtCore.QRect(10, 60, 1171, 571))
        self.train_img.setText("")
        self.train_img.setPixmap(QtGui.QPixmap(self.model_path+"results.png"))
        self.train_img.setScaledContents(True)
        self.train_img.setObjectName("train_img")
        self.train_labe = QtWidgets.QLabel(parent=self.train_tab)
        self.train_labe.setGeometry(QtCore.QRect(40, 25, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.train_labe.setFont(font)
        self.train_labe.setObjectName("train_label")
        self.menu.addTab(self.train_tab, "Train")
        self.matrix_tab = QtWidgets.QWidget()
        self.matrix_tab.setObjectName("matrix_tab")
        self.matrix_label = QtWidgets.QLabel(parent=self.matrix_tab)
        self.matrix_label.setGeometry(QtCore.QRect(40, 25, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_label.setFont(font)
        self.matrix_label.setObjectName("matrix_label")
        self.matrix_img = QtWidgets.QLabel(parent=self.matrix_tab)
        self.matrix_img.setGeometry(QtCore.QRect(110, 60, 1021, 611))
        self.matrix_img.setText("")
        self.matrix_img.setPixmap(QtGui.QPixmap(self.model_path+"confusion_matrix.png"))
        self.matrix_img.setScaledContents(True)
        self.matrix_img.setObjectName("matrix_img")
        self.menu.addTab(self.matrix_tab, "Matrix")
        self.labels_tab = QtWidgets.QWidget()
        self.labels_tab.setObjectName("labels_tab")
        self.labels_label = QtWidgets.QLabel(parent=self.labels_tab)
        self.labels_label.setGeometry(QtCore.QRect(40, 25, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labels_label.setFont(font)
        self.labels_label.setObjectName("labels_label")
        self.labels_img = QtWidgets.QLabel(parent=self.labels_tab)
        self.labels_img.setGeometry(QtCore.QRect(160, 50, 891, 611))
        self.labels_img.setText("")
        self.labels_img.setPixmap(QtGui.QPixmap(self.model_path+"labels.jpg"))
        self.labels_img.setScaledContents(True)
        self.labels_img.setObjectName("labels_img")
        self.menu.addTab(self.labels_tab, "Labels")
        self.author_name = QtWidgets.QLabel(parent=model_info_win)
        self.author_name.setGeometry(QtCore.QRect(1080, 680, 101, 16))
        self.author_name.setText("Bruno Guiomar")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.author_name.setFont(font)
        self.author_name.setObjectName("author_name")

        self.retranslateUi(model_info_win)
        self.menu.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(model_info_win)

    def retranslateUi(self, model_info_win):
        _translate = QtCore.QCoreApplication.translate
        self.train_labe.setText(_translate("model_info_win", "Train Information"))
        self.matrix_label.setText(_translate("model_info_win", "Confusion Matrix"))
        self.labels_label.setText(_translate("model_info_win", "Label Details"))
