from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QLabel, QPushButton, QWidget, QMenuBar, QMenu

from screeninfo import get_monitors

import utils.file_operations as file_operator
import inference_modules.inference_engine
from GRS_model_info import Ui_model_info_win
from GRS_inference_preview import Ui_inference_preview_win
from GRS_about_page import Ui_GRS_about_page

#LED_ON_CSS = "background-color: rgb(146, 221, 155);\n""border-style: solid;\n""border-width: 2px;\n""border-color: rgb(163, 163, 163)"
LED_ON_CSS = "background-color: rgb(146, 221, 155);"

#LED_OFF_CSS = "background-color: rgb(191, 194, 197);\n""border-style: solid;\n""border-width: 2px;\n""border-color: rgb(163, 163, 163)"
LED_OFF_CSS = "background-color: rgb(191, 194, 197);"


class Model_Info_Window(QWidget, Ui_model_info_win):
    def __init__(self, model_name):
        super().__init__()
        self.setupUi(self, model_name)

class Inference_Preview_Window(QWidget, Ui_inference_preview_win):
    def __init__(self, width, height):
        super().__init__()
        self.setupUi(self, width, height)

class About_Page_Window(QWidget, Ui_GRS_about_page):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


class Ui_MainWindow(object):
    def __init__(self):
        self.inference_engine = None
        self.detected_classes = []
        self.model_info_win = None
        self.inference_preview_win = None
        self.config = {}

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(927, 522)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.Germany))
        MainWindow.setWindowIcon(QtGui.QIcon("resources/img/window_icons/GRS_mainWindow_icon.png"))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(820, 500, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mainSignal_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.mainSignal_group.setGeometry(QtCore.QRect(20, 30, 281, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        self.menuBar = QMenuBar(parent=self.centralwidget)
        # Creating menus using a QMenu object
        self.help_menu = QMenu("&Help", self)
        self.menuBar.addMenu(self.help_menu)
        self.help_menu.addAction("About", self.open_about_page)

        self.mainSignal_group.setFont(font)
        self.mainSignal_group.setObjectName("mainSignal_group")
        self.MS_hp0_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp0_label.setGeometry(QtCore.QRect(60, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_hp0_label.setFont(font)
        self.MS_hp0_label.setText("Hp 0")
        self.MS_hp0_label.setObjectName("MS_hp0_label")
        self.MS_hp1_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp1_label.setGeometry(QtCore.QRect(60, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_hp1_label.setFont(font)
        self.MS_hp1_label.setText("Hp 1")
        self.MS_hp1_label.setObjectName("MS_hp1_label")
        self.MS_hp2_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp2_label.setGeometry(QtCore.QRect(60, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_hp2_label.setFont(font)
        self.MS_hp2_label.setText("Hp 2")
        self.MS_hp2_label.setObjectName("MS_hp2_label")
        self.MS_line1 = QtWidgets.QFrame(parent=self.mainSignal_group)
        self.MS_line1.setGeometry(QtCore.QRect(0, 240, 281, 16))
        self.MS_line1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.MS_line1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.MS_line1.setObjectName("MS_line1")
        self.MS_vr1_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr1_label.setGeometry(QtCore.QRect(60, 370, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_vr1_label.setFont(font)
        self.MS_vr1_label.setText("Vr 1")
        self.MS_vr1_label.setObjectName("MS_vr1_label")
        self.MS_vr0_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr0_label.setGeometry(QtCore.QRect(60, 310, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_vr0_label.setFont(font)
        self.MS_vr0_label.setText("Vr 0")
        self.MS_vr0_label.setObjectName("MS_vr0_label")
        self.MS_vr2_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr2_label.setGeometry(QtCore.QRect(60, 430, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_vr2_label.setFont(font)
        self.MS_vr2_label.setText("Vr 2")
        self.MS_vr2_label.setObjectName("MS_vr2_label")
        self.MS_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_label.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_label.setFont(font)
        self.MS_label.setObjectName("MS_label")
        self.MS_label2 = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_label2.setGeometry(QtCore.QRect(10, 270, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MS_label2.setFont(font)
        self.MS_label2.setObjectName("MS_label2")
        self.MS_hp1_icon = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp1_icon.setGeometry(QtCore.QRect(15, 133, 21, 41))
        self.MS_hp1_icon.setText("")
        self.MS_hp1_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/hp1_icon.gif"))
        self.MS_hp1_icon.setScaledContents(True)
        self.MS_hp1_icon.setObjectName("MS_hp1_icon")
        self.MS_hp0_icon = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp0_icon.setGeometry(QtCore.QRect(15, 73, 21, 41))
        self.MS_hp0_icon.setText("")
        self.MS_hp0_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/hp0_icon.gif"))
        self.MS_hp0_icon.setScaledContents(True)
        self.MS_hp0_icon.setObjectName("MS_hp0_icon")
        self.MS_hp2_icon = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp2_icon.setGeometry(QtCore.QRect(20, 190, 21, 41))
        self.MS_hp2_icon.setText("")
        self.MS_hp2_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/hp2_icon.gif"))
        self.MS_hp2_icon.setScaledContents(True)
        self.MS_hp2_icon.setObjectName("MS_hp2_icon")
        self.MS_vr0_icon = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr0_icon.setGeometry(QtCore.QRect(10, 300, 41, 41))
        self.MS_vr0_icon.setText("")
        self.MS_vr0_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/vr0_icon.gif"))
        self.MS_vr0_icon.setScaledContents(True)
        self.MS_vr0_icon.setObjectName("MS_vr0_icon")
        self.MS_vr1_icon = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr1_icon.setGeometry(QtCore.QRect(10, 360, 41, 41))
        self.MS_vr1_icon.setText("")
        self.MS_vr1_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/vr1_icon.gif"))
        self.MS_vr1_icon.setScaledContents(True)
        self.MS_vr1_icon.setObjectName("MS_vr1_icon")
        self.MS_vr2_icon = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr2_icon.setGeometry(QtCore.QRect(10, 420, 41, 41))
        self.MS_vr2_icon.setText("")
        self.MS_vr2_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/vr2_icon.gif"))
        self.MS_vr2_icon.setScaledContents(True)
        self.MS_vr2_icon.setObjectName("MS_vr2_icon")
        self.MS_active_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_active_label.setGeometry(QtCore.QRect(150, 40, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MS_active_label.setFont(font)
        self.MS_active_label.setObjectName("MS_active_label")
        self.MS_line2 = QtWidgets.QFrame(parent=self.mainSignal_group)
        self.MS_line2.setGeometry(QtCore.QRect(113, 70, 20, 171))
        self.MS_line2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.MS_line2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.MS_line2.setObjectName("MS_line2")
        self.MS_conf_label = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_conf_label.setGeometry(QtCore.QRect(220, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MS_conf_label.setFont(font)
        self.MS_conf_label.setObjectName("MS_conf_label")
        self.MS_line3 = QtWidgets.QFrame(parent=self.mainSignal_group)
        self.MS_line3.setGeometry(QtCore.QRect(113, 310, 20, 151))
        self.MS_line3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.MS_line3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.MS_line3.setObjectName("MS_line3")
        self.MS_active_label2 = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_active_label2.setGeometry(QtCore.QRect(150, 270, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MS_active_label2.setFont(font)
        self.MS_active_label2.setObjectName("MS_active_label2")
        self.MS_conf_label2 = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_conf_label2.setGeometry(QtCore.QRect(220, 270, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MS_conf_label2.setFont(font)
        self.MS_conf_label2.setObjectName("MS_conf_label2")
        self.MS_hp0_led = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp0_led.setGeometry(QtCore.QRect(160, 83, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MS_hp0_led.setFont(font)
        self.MS_hp0_led.setStyleSheet(LED_OFF_CSS)
        self.MS_hp0_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MS_hp0_led.setLineWidth(0)
        self.MS_hp0_led.setText("")
        self.MS_hp0_led.setObjectName("hp0_led")
        self.MS_hp0_led.setEnabled(False)
        self.MS_hp1_led = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp1_led.setGeometry(QtCore.QRect(160, 143, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MS_hp1_led.setFont(font)
        self.MS_hp1_led.setStyleSheet(LED_OFF_CSS)
        self.MS_hp1_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MS_hp1_led.setLineWidth(0)
        self.MS_hp1_led.setText("")
        self.MS_hp1_led.setObjectName("hp1_led")
        self.MS_hp1_led.setEnabled(False)
        self.MS_hp2_led = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp2_led.setGeometry(QtCore.QRect(160, 203, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MS_hp2_led.setFont(font)
        self.MS_hp2_led.setStyleSheet(LED_OFF_CSS)
        self.MS_hp2_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MS_hp2_led.setLineWidth(0)
        self.MS_hp2_led.setText("")
        self.MS_hp2_led.setObjectName("hp2_led")
        self.MS_hp2_led.setEnabled(False)
        self.MS_vr0_led = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr0_led.setGeometry(QtCore.QRect(160, 315, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MS_vr0_led.setFont(font)
        self.MS_vr0_led.setStyleSheet(LED_OFF_CSS)
        self.MS_vr0_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MS_vr0_led.setLineWidth(0)
        self.MS_vr0_led.setText("")
        self.MS_vr0_led.setObjectName("vr0_led")
        self.MS_vr0_led.setEnabled(False)
        self.MS_vr1_led = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr1_led.setGeometry(QtCore.QRect(160, 375, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MS_vr1_led.setFont(font)
        self.MS_vr1_led.setStyleSheet(LED_OFF_CSS)
        self.MS_vr1_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MS_vr1_led.setLineWidth(0)
        self.MS_vr1_led.setText("")
        self.MS_vr1_led.setObjectName("vr1_led")
        self.MS_vr1_led.setEnabled(False)
        self.MS_vr2_led = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr2_led.setGeometry(QtCore.QRect(160, 435, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.MS_vr2_led.setFont(font)
        self.MS_vr2_led.setStyleSheet(LED_OFF_CSS)
        self.MS_vr2_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MS_vr2_led.setLineWidth(0)
        self.MS_vr2_led.setText("")
        self.MS_vr2_led.setObjectName("vr2_led")
        self.MS_vr2_led.setEnabled(False)
        self.MS_vr0_conf_value = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr0_conf_value.setGeometry(QtCore.QRect(212, 318, 55, 16))
        self.MS_vr0_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MS_vr0_conf_value.setObjectName("vr0_conf_value")
        self.MS_vr1_conf_value = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr1_conf_value.setGeometry(QtCore.QRect(212, 378, 55, 16))
        self.MS_vr1_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MS_vr1_conf_value.setObjectName("vr1_conf_value")
        self.MS_vr2_conf_value = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_vr2_conf_value.setGeometry(QtCore.QRect(212, 438, 55, 16))
        self.MS_vr2_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MS_vr2_conf_value.setObjectName("vr2_conf_value")
        self.MS_hp0_conf_value = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp0_conf_value.setGeometry(QtCore.QRect(210, 86, 55, 16))
        self.MS_hp0_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MS_hp0_conf_value.setObjectName("hp0_conf_value")
        self.MS_hp1_conf_value = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp1_conf_value.setGeometry(QtCore.QRect(210, 146, 55, 16))
        self.MS_hp1_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MS_hp1_conf_value.setObjectName("hp1_conf_value")
        self.MS_hp2_conf_value = QtWidgets.QLabel(parent=self.mainSignal_group)
        self.MS_hp2_conf_value.setGeometry(QtCore.QRect(210, 206, 55, 16))
        self.MS_hp2_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MS_hp2_conf_value.setObjectName("hp2_conf_value")
        self.combinationSignal_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.combinationSignal_group.setGeometry(QtCore.QRect(320, 30, 261, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.combinationSignal_group.setFont(font)
        self.combinationSignal_group.setObjectName("combinationSignal_group")
        self.CS_ks2_label = QtWidgets.QLabel(parent=self.combinationSignal_group)
        self.CS_ks2_label.setGeometry(QtCore.QRect(60, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CS_ks2_label.setFont(font)
        self.CS_ks2_label.setText("Ks 2")
        self.CS_ks2_label.setObjectName("CS_ks2_label")
        self.CS_ks2_icon = QtWidgets.QLabel(parent=self.combinationSignal_group)
        self.CS_ks2_icon.setGeometry(QtCore.QRect(10, 33, 31, 51))
        self.CS_ks2_icon.setText("")
        self.CS_ks2_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/ks2_icon.gif"))
        self.CS_ks2_icon.setScaledContents(True)
        self.CS_ks2_icon.setObjectName("CS_ks2_icon")
        self.CS_ks2_conf_label = QtWidgets.QLabel(parent=self.combinationSignal_group)
        self.CS_ks2_conf_label.setGeometry(QtCore.QRect(210, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_ks2_conf_label.setFont(font)
        self.CS_ks2_conf_label.setObjectName("CS_ks2_conf_label")
        self.CS_ks2_active_label = QtWidgets.QLabel(parent=self.combinationSignal_group)
        self.CS_ks2_active_label.setGeometry(QtCore.QRect(140, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_ks2_active_label.setFont(font)
        self.CS_ks2_active_label.setObjectName("CS_ks2_active_label")
        self.CS_ks2_active_led = QtWidgets.QLabel(parent=self.combinationSignal_group)
        self.CS_ks2_active_led.setGeometry(QtCore.QRect(152, 55, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CS_ks2_active_led.setFont(font)
        self.CS_ks2_active_led.setStyleSheet(LED_OFF_CSS)
        self.CS_ks2_active_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.CS_ks2_active_led.setLineWidth(0)
        self.CS_ks2_active_led.setText("")
        self.CS_ks2_active_led.setObjectName("ks2_led")
        self.CS_ks2_active_led.setEnabled(False)
        self.CS_ks2_conf_value = QtWidgets.QLabel(parent=self.combinationSignal_group)
        self.CS_ks2_conf_value.setGeometry(QtCore.QRect(200, 58, 55, 16))
        self.CS_ks2_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CS_ks2_conf_value.setObjectName("ks2_conf_value")
        self.protectionSignal_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.protectionSignal_group.setGeometry(QtCore.QRect(320, 130, 261, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.protectionSignal_group.setFont(font)
        self.protectionSignal_group.setObjectName("protectionSignal_group")
        self.PS_sh2_label = QtWidgets.QLabel(parent=self.protectionSignal_group)
        self.PS_sh2_label.setGeometry(QtCore.QRect(60, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PS_sh2_label.setFont(font)
        self.PS_sh2_label.setText("Sh 2")
        self.PS_sh2_label.setObjectName("PS_sh2_label")
        self.PS_sh2_icon = QtWidgets.QLabel(parent=self.protectionSignal_group)
        self.PS_sh2_icon.setGeometry(QtCore.QRect(10, 55, 37, 21))
        self.PS_sh2_icon.setText("")
        self.PS_sh2_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/sh2_icon.gif"))
        self.PS_sh2_icon.setScaledContents(True)
        self.PS_sh2_icon.setObjectName("PS_sh2_icon")
        self.PS_conf_label = QtWidgets.QLabel(parent=self.protectionSignal_group)
        self.PS_conf_label.setGeometry(QtCore.QRect(210, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.PS_conf_label.setFont(font)
        self.PS_conf_label.setObjectName("PS_conf_label")
        self.PS_active_label = QtWidgets.QLabel(parent=self.protectionSignal_group)
        self.PS_active_label.setGeometry(QtCore.QRect(140, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.PS_active_label.setFont(font)
        self.PS_active_label.setObjectName("PS_active_label")
        self.PS_sh2_led = QtWidgets.QLabel(parent=self.protectionSignal_group)
        self.PS_sh2_led.setGeometry(QtCore.QRect(152, 55, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PS_sh2_led.setFont(font)
        self.PS_sh2_led.setStyleSheet(LED_OFF_CSS)
        self.PS_sh2_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.PS_sh2_led.setLineWidth(0)
        self.PS_sh2_led.setText("")
        self.PS_sh2_led.setObjectName("sh2_led")
        self.PS_sh2_led.setEnabled(False)
        self.PS_sh2_conf_value = QtWidgets.QLabel(parent=self.protectionSignal_group)
        self.PS_sh2_conf_value.setGeometry(QtCore.QRect(200, 58, 55, 16))
        self.PS_sh2_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PS_sh2_conf_value.setObjectName("sh2_conf_value")
        self.secondarySignals_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.secondarySignals_group.setGeometry(QtCore.QRect(320, 230, 261, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.secondarySignals_group.setFont(font)
        self.secondarySignals_group.setObjectName("secondarySignals_group")
        self.SS_ne2_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne2_label.setGeometry(QtCore.QRect(50, 55, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SS_ne2_label.setFont(font)
        self.SS_ne2_label.setText("Ne 2")
        self.SS_ne2_label.setObjectName("SS_ne2_label")
        self.SS_ne3100_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3100_label.setGeometry(QtCore.QRect(50, 97, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne3100_label.setFont(font)
        self.SS_ne3100_label.setText("Ne 3-100")
        self.SS_ne3100_label.setObjectName("SS_ne3100_label")
        self.SS_ne3175_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3175_label.setGeometry(QtCore.QRect(50, 143, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(False)
        self.SS_ne3175_label.setFont(font)
        self.SS_ne3175_label.setText("Ne 3-175")
        self.SS_ne3175_label.setObjectName("SS_ne3175_label")
        self.SS_ne3250_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3250_label.setGeometry(QtCore.QRect(50, 188, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne3250_label.setFont(font)
        self.SS_ne3250_label.setText("Ne 3-250")
        self.SS_ne3250_label.setObjectName("SS_ne3250_label")
        self.SS_ne5_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne5_label.setGeometry(QtCore.QRect(50, 233, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SS_ne5_label.setFont(font)
        self.SS_ne5_label.setText("Ne 5")
        self.SS_ne5_label.setObjectName("SS_ne5_label")
        self.SS_ne3100_icon = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3100_icon.setGeometry(QtCore.QRect(20, 93, 16, 41))
        self.SS_ne3100_icon.setText("")
        self.SS_ne3100_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/ne3_100_icon.gif"))
        self.SS_ne3100_icon.setScaledContents(True)
        self.SS_ne3100_icon.setObjectName("SS_ne3100_icon")
        self.SS_ne3175_icon = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3175_icon.setGeometry(QtCore.QRect(20, 140, 16, 41))
        self.SS_ne3175_icon.setText("")
        self.SS_ne3175_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/ne3_175_icon.gif"))
        self.SS_ne3175_icon.setScaledContents(True)
        self.SS_ne3175_icon.setObjectName("SS_ne3175_icon")
        self.SS_ne3250_icon = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3250_icon.setGeometry(QtCore.QRect(20, 187, 16, 41))
        self.SS_ne3250_icon.setText("")
        self.SS_ne3250_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/ne3_250_icon.gif"))
        self.SS_ne3250_icon.setScaledContents(True)
        self.SS_ne3250_icon.setObjectName("SS_ne3250_icon")
        self.SS_ne5_icon = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne5_icon.setGeometry(QtCore.QRect(17, 235, 21, 31))
        self.SS_ne5_icon.setText("")
        self.SS_ne5_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/ne5_icon.gif"))
        self.SS_ne5_icon.setScaledContents(True)
        self.SS_ne5_icon.setObjectName("SS_ne5_icon")
        self.SS_ne2_icon = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne2_icon.setGeometry(QtCore.QRect(17, 48, 21, 41))
        self.SS_ne2_icon.setText("")
        self.SS_ne2_icon.setPixmap(QtGui.QPixmap("resources/img/signal_icons/ne2_icon.gif"))
        self.SS_ne2_icon.setScaledContents(True)
        self.SS_ne2_icon.setObjectName("SS_ne2_icon")
        self.SS_active_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_active_label.setGeometry(QtCore.QRect(140, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.SS_active_label.setFont(font)
        self.SS_active_label.setObjectName("SS_active_label")
        self.SS_conf_label = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_conf_label.setGeometry(QtCore.QRect(210, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.SS_conf_label.setFont(font)
        self.SS_conf_label.setObjectName("SS_conf_label")
        self.SS_line1 = QtWidgets.QFrame(parent=self.secondarySignals_group)
        self.SS_line1.setGeometry(QtCore.QRect(123, 30, 20, 231))
        self.SS_line1.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.SS_line1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.SS_line1.setObjectName("SS_line1")
        self.SS_ne2_led = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne2_led.setGeometry(QtCore.QRect(152, 60, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne2_led.setFont(font)
        self.SS_ne2_led.setStyleSheet(LED_OFF_CSS)
        self.SS_ne2_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.SS_ne2_led.setLineWidth(0)
        self.SS_ne2_led.setText("")
        self.SS_ne2_led.setObjectName("ne2_led")
        self.SS_ne2_led.setEnabled(False)
        self.SS_ne3100_led = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3100_led.setGeometry(QtCore.QRect(152, 102, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne3100_led.setFont(font)
        self.SS_ne3100_led.setStyleSheet(LED_OFF_CSS)
        self.SS_ne3100_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.SS_ne3100_led.setLineWidth(0)
        self.SS_ne3100_led.setText("")
        self.SS_ne3100_led.setObjectName("ne3_100_led")
        self.SS_ne3100_led.setEnabled(False)
        self.SS_ne3175_led = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3175_led.setGeometry(QtCore.QRect(152, 147, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne3175_led.setFont(font)
        self.SS_ne3175_led.setStyleSheet(LED_OFF_CSS)
        self.SS_ne3175_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.SS_ne3175_led.setLineWidth(0)
        self.SS_ne3175_led.setText("")
        self.SS_ne3175_led.setObjectName("ne3_175_led")
        self.SS_ne3175_led.setEnabled(False)
        self.SS_ne3250_led = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3250_led.setGeometry(QtCore.QRect(152, 193, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne3250_led.setFont(font)
        self.SS_ne3250_led.setStyleSheet(LED_OFF_CSS)
        self.SS_ne3250_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.SS_ne3250_led.setLineWidth(0)
        self.SS_ne3250_led.setText("")
        self.SS_ne3250_led.setObjectName("ne3_250_led")
        self.SS_ne3250_led.setEnabled(False)
        self.SS_ne5_led = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne5_led.setGeometry(QtCore.QRect(152, 235, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SS_ne5_led.setFont(font)
        self.SS_ne5_led.setStyleSheet(LED_OFF_CSS)
        self.SS_ne5_led.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.SS_ne5_led.setLineWidth(0)
        self.SS_ne5_led.setText("")
        self.SS_ne5_led.setObjectName("ne5_led")
        self.SS_ne5_led.setEnabled(False)
        self.SS_ne2_conf_value = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne2_conf_value.setGeometry(QtCore.QRect(200, 63, 55, 16))
        self.SS_ne2_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SS_ne2_conf_value.setObjectName("ne2_conf_value")
        self.SS_ne3100_conf_value = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3100_conf_value.setGeometry(QtCore.QRect(200, 105, 55, 16))
        self.SS_ne3100_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SS_ne3100_conf_value.setObjectName("ne3_100_conf_value")
        self.SS_ne3175_conf_value = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3175_conf_value.setGeometry(QtCore.QRect(200, 150, 55, 16))
        self.SS_ne3175_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SS_ne3175_conf_value.setObjectName("ne3_175_conf_value")
        self.SS_ne3250_conf_value = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne3250_conf_value.setGeometry(QtCore.QRect(200, 196, 55, 16))
        self.SS_ne3250_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SS_ne3250_conf_value.setObjectName("ne3_250_conf_value")
        self.SS_ne5_conf_value = QtWidgets.QLabel(parent=self.secondarySignals_group)
        self.SS_ne5_conf_value.setGeometry(QtCore.QRect(200, 238, 55, 16))
        self.SS_ne5_conf_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.SS_ne5_conf_value.setObjectName("ne5_conf_value")
        self.inferenceInformation_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.inferenceInformation_group.setGeometry(QtCore.QRect(660, 40, 211, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inferenceInformation_group.setFont(font)
        self.inferenceInformation_group.setObjectName("inferenceInformation_group")
        self.II_preProcess_label = QtWidgets.QLabel(parent=self.inferenceInformation_group)
        self.II_preProcess_label.setGeometry(QtCore.QRect(10, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.II_preProcess_label.setFont(font)
        self.II_preProcess_label.setText("Pre-Process")
        self.II_preProcess_label.setObjectName("II_preProcess_label")
        self.II_inference_label = QtWidgets.QLabel(parent=self.inferenceInformation_group)
        self.II_inference_label.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.II_inference_label.setFont(font)
        self.II_inference_label.setText("Inference")
        self.II_inference_label.setObjectName("II_inference_label")
        self.II_postProcess_label = QtWidgets.QLabel(parent=self.inferenceInformation_group)
        self.II_postProcess_label.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.II_postProcess_label.setFont(font)
        self.II_postProcess_label.setText("Post-Process")
        self.II_postProcess_label.setObjectName("II_postProcess_label")
        self.II_separator1 = QtWidgets.QFrame(parent=self.inferenceInformation_group)
        self.II_separator1.setGeometry(QtCore.QRect(120, 40, 20, 111))
        self.II_separator1.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.II_separator1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.II_separator1.setObjectName("II_separator1")
        self.II_preProcess_value = QtWidgets.QLabel(parent=self.inferenceInformation_group)
        self.II_preProcess_value.setGeometry(QtCore.QRect(140, 47, 55, 16))
        self.II_preProcess_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.II_preProcess_value.setObjectName("II_preProcess_value")
        self.II_inference_value = QtWidgets.QLabel(parent=self.inferenceInformation_group)
        self.II_inference_value.setGeometry(QtCore.QRect(140, 87, 55, 16))
        self.II_inference_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.II_inference_value.setObjectName("II_inference_value")
        self.II_postProcess_value = QtWidgets.QLabel(parent=self.inferenceInformation_group)
        self.II_postProcess_value.setGeometry(QtCore.QRect(140, 127, 55, 16))
        self.II_postProcess_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.II_postProcess_value.setObjectName("II_postProcess_value")
        self.controls_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.controls_group.setGeometry(QtCore.QRect(610, 370, 261, 121))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.controls_group.setFont(font)
        self.controls_group.setObjectName("controls_group")
        self.CG_start_button = QtWidgets.QPushButton(parent=self.controls_group)
        self.CG_start_button.setEnabled(True)
        self.CG_start_button.setGeometry(QtCore.QRect(20, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CG_start_button.setFont(font)
        self.CG_start_button.setStyleSheet("")
        self.CG_start_button.setCheckable(False)
        self.CG_start_button.setFlat(False)
        self.CG_start_button.setObjectName("CG_start_button")
        self.CG_start_button.clicked.connect(self.start_inference)
        self.CG_stop_button = QtWidgets.QPushButton(parent=self.controls_group)
        self.CG_stop_button.setGeometry(QtCore.QRect(140, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.CG_stop_button.setFont(font)
        self.CG_stop_button.setStyleSheet("")
        self.CG_stop_button.setObjectName("CG_stop_button")
        self.CG_stop_button.setDisabled(True)
        self.CG_stop_button.clicked.connect(self.stop_inference)
        self.options_group = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.options_group.setGeometry(QtCore.QRect(610, 220, 301, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.options_group.setFont(font)
        self.options_group.setObjectName("options_group")

        self.OPT_model_box = QtWidgets.QComboBox(parent=self.options_group)
        self.OPT_model_box.setGeometry(QtCore.QRect(10, 50, 101, 22))
        self.OPT_model_box.setObjectName("OPT_model_box")
        model_list = file_operator.list_models()
        self.OPT_model_box.addItems(model_list.keys())
        self.OPT_model_box.setCurrentIndex(0)
        self.OPT_model_box.activated.connect(self.update_model_option)
        for index, item in enumerate(model_list):
            self.OPT_model_box.setItemIcon(index, QIcon(model_list[item]))

        self.OPT_model_label = QtWidgets.QLabel(parent=self.options_group)
        self.OPT_model_label.setGeometry(QtCore.QRect(10, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OPT_model_label.setFont(font)
        self.OPT_model_label.setObjectName("OPT_model_label")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OPT_input_box = QtWidgets.QComboBox(parent=self.options_group)
        self.OPT_input_box.setGeometry(QtCore.QRect(10, 100, 101, 22))
        self.OPT_input_box.setFont(font)
        self.OPT_input_box.setObjectName("OPT_input_box")
        self.OPT_input_box.setCurrentIndex(0)
        self.OPT_input_box.activated.connect(self.update_input_option)
        self.OPT_input_box.addItems(["Screen"])
        self.OPT_input_box.setCurrentIndex(0)
        self.OPT_input_label = QtWidgets.QLabel(parent=self.options_group)
        self.OPT_input_label.setGeometry(QtCore.QRect(10, 80, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OPT_input_label.setFont(font)
        self.OPT_input_label.setObjectName("OPT_input_label")
        self.OPT_proportion_box = QtWidgets.QComboBox(parent=self.options_group)
        self.OPT_proportion_box.setGeometry(QtCore.QRect(160, 50, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OPT_proportion_box.setFont(font)
        self.OPT_proportion_box.setObjectName("OPT_proportion_box")
        self.OPT_proportion_box.activated.connect(self.update_proportion_option)
        self.OPT_proportion_box.addItems(["Half", "Full"])
        self.OPT_proportion_box.setCurrentIndex(0)
        self.OPT_proportion_label = QtWidgets.QLabel(parent=self.options_group)
        self.OPT_proportion_label.setGeometry(QtCore.QRect(160, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OPT_proportion_label.setFont(font)
        self.OPT_proportion_label.setObjectName("OPT_proportion_label")
        self.OPT_preview = QtWidgets.QCheckBox(parent=self.options_group)
        self.OPT_preview.setGeometry(QtCore.QRect(160, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OPT_preview.setFont(font)
        self.OPT_preview.setObjectName("OPT_preview")
        self.OPT_preview.stateChanged.connect(self.update_preview_option)
        self.OPT_model_info = QtWidgets.QPushButton(parent=self.options_group)
        self.OPT_model_info.setGeometry(QtCore.QRect(115, 50, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.OPT_model_info.setFont(font)
        self.OPT_model_info.setObjectName("OPT_model_info")
        self.OPT_model_info.clicked.connect(self.show_model_info_win)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GRS Dashboard"))
        self.label.setText(_translate("MainWindow", "Bruno Guiomar"))
        self.mainSignal_group.setTitle(_translate("MainWindow", "Hauptsignal"))
        self.MS_label.setText(_translate("MainWindow", "Main Signal"))
        self.MS_label2.setText(_translate("MainWindow", "Distant Signal"))
        self.MS_active_label.setText(_translate("MainWindow", "Active"))
        self.MS_conf_label.setText(_translate("MainWindow", "Conf."))
        self.MS_active_label2.setText(_translate("MainWindow", "Active"))
        self.MS_conf_label2.setText(_translate("MainWindow", "Conf."))
        self.MS_vr0_conf_value.setText(_translate("MainWindow", "0.0"))
        self.MS_vr1_conf_value.setText(_translate("MainWindow", "0.0"))
        self.MS_vr2_conf_value.setText(_translate("MainWindow", "0.0"))
        self.MS_hp0_conf_value.setText(_translate("MainWindow", "0.0"))
        self.MS_hp1_conf_value.setText(_translate("MainWindow", "0.0"))
        self.MS_hp2_conf_value.setText(_translate("MainWindow", "0.0"))
        self.combinationSignal_group.setTitle(_translate("MainWindow", "Kombinationssignal"))
        self.CS_ks2_conf_label.setText(_translate("MainWindow", "Conf."))
        self.CS_ks2_active_label.setText(_translate("MainWindow", "Active"))
        self.CS_ks2_conf_value.setText(_translate("MainWindow", "0.0"))
        self.protectionSignal_group.setTitle(_translate("MainWindow", "Schutzsignale"))
        self.PS_conf_label.setText(_translate("MainWindow", "Conf."))
        self.PS_active_label.setText(_translate("MainWindow", "Active"))
        self.PS_sh2_conf_value.setText(_translate("MainWindow", "0.0"))
        self.secondarySignals_group.setTitle(_translate("MainWindow", "Nebensignale"))
        self.SS_active_label.setText(_translate("MainWindow", "Active"))
        self.SS_conf_label.setText(_translate("MainWindow", "Conf."))
        self.SS_ne2_conf_value.setText(_translate("MainWindow", "0.0"))
        self.SS_ne3100_conf_value.setText(_translate("MainWindow", "0.0"))
        self.SS_ne3175_conf_value.setText(_translate("MainWindow", "0.0"))
        self.SS_ne3250_conf_value.setText(_translate("MainWindow", "0.0"))
        self.SS_ne5_conf_value.setText(_translate("MainWindow", "0.0"))
        self.inferenceInformation_group.setTitle(_translate("MainWindow", "Inference Information"))
        self.II_preProcess_value.setText(_translate("MainWindow", "0.0"))
        self.II_inference_value.setText(_translate("MainWindow", "0.0"))
        self.II_postProcess_value.setText(_translate("MainWindow", "0.0"))
        self.controls_group.setTitle(_translate("MainWindow", "Controls"))
        self.CG_start_button.setText(_translate("MainWindow", "Start"))
        self.CG_stop_button.setText(_translate("MainWindow", "Stop"))
        self.options_group.setTitle(_translate("MainWindow", "Options"))
        self.OPT_model_label.setText(_translate("MainWindow", "Model"))
        self.OPT_input_label.setText(_translate("MainWindow", "Input"))
        self.OPT_proportion_label.setText(_translate("MainWindow", "Proportion"))
        self.OPT_preview.setText(_translate("MainWindow", "Preview"))
        self.OPT_model_info.setText(_translate("MainWindow", "?"))


    # CG Action Handler
    def start_inference(self):
        print("Start Button")

        # Create Inference Engine
        self.config = {
            "model_name": self.OPT_model_box.currentText(),
            "proportion": self.OPT_proportion_box.currentText(),
            "input": self.OPT_input_box.currentText(),
            "preview": self.OPT_preview.isChecked()
        }
        self.inference_engine = inference_modules.inference_engine.InferenceEngine(self.config, self)

        # Open Inference Preview Window
        if self.OPT_preview.isChecked():
            self.show_inference_preview_win()

        self.CG_start_button.setDisabled(True)
        self.inference_engine.start_inference()
        self.CG_stop_button.setDisabled(False)
        self.options_group.setDisabled(True)

    def stop_inference(self):
        print("Stop Button")

        self.CG_stop_button.setDisabled(True)

        # Stop Inference
        self.inference_engine.stop_inference()
        # Close Inference Preview Window
        if self.inference_preview_win is not None:
            self.inference_preview_win.close()
        # Reset GUI Elements
        self.reset_gui_elements()

        self.CG_start_button.setDisabled(False)
        self.options_group.setDisabled(False)


    def show_model_info_win(self):
        self.model_info_win = Model_Info_Window(self.OPT_model_box.currentText())
        self.model_info_win.show()

    def show_inference_preview_win(self):
        self.inference_preview_win = Inference_Preview_Window(int(get_monitors()[0].width/2)-200, get_monitors()[0].height-300)
        self.inference_preview_win.show()

    def update_inference_preview_win(self, updated_frame):
        print("Inference Preview Update")
        updated_frame = QtGui.QImage(updated_frame.data, updated_frame.shape[1], updated_frame.shape[0], QtGui.QImage.Format.Format_RGB888).rgbSwapped()
        self.inference_preview_win.update_inference_img(updated_frame)

    def update_model_option(self):
        self.config["model_name"] = self.OPT_model_box.currentText()

    def update_input_option(self):
        self.config["input"] = self.OPT_input_box.currentText()

    def update_proportion_option(self):
        self.config["proportion"] = self.OPT_proportion_box.currentText()

    def update_preview_option(self):
        self.config["preview"] = self.OPT_preview.isChecked()

    def update_detected_classes(self, detected_classes):
        print(detected_classes)

        if detected_classes:
            for class_name in detected_classes:
                selected_led_obj = self.centralwidget.findChild(QLabel, class_name.lower()+"_led")
                selected_conf_obj = self.centralwidget.findChild(QLabel, class_name.lower()+"_conf_value")
                print(class_name.lower())
                if not selected_led_obj.isEnabled():
                    # Led Update
                    selected_led_obj.setStyleSheet(LED_ON_CSS)
                    selected_led_obj.setEnabled(True)
                    self.detected_classes.append(class_name)
                    # Conf Update
                    selected_conf_obj.setText("%.2f" % round(detected_classes[class_name], 2))
        else:
            if self.detected_classes:
                for c in self.detected_classes:
                    # Led Update
                    selected_led_obj = self.centralwidget.findChild(QLabel, c.lower() + "_led")
                    selected_led_obj.setStyleSheet(LED_OFF_CSS)
                    selected_led_obj.setEnabled(False)
                    self.detected_classes.remove(c)
                    # Conf Update
                    selected_conf_obj = self.centralwidget.findChild(QLabel, c.lower() + "_conf_value")
                    selected_conf_obj.setText("0.0")

        s = set(detected_classes)
        temp3 = [x for x in self.detected_classes if x not in s]

        for c in temp3:
            # Led Update
            selected_led_obj = self.centralwidget.findChild(QLabel, c.lower() + "_led")
            selected_led_obj.setStyleSheet(LED_OFF_CSS)
            selected_led_obj.setEnabled(False)
            self.detected_classes.remove(c)
            # Conf Update
            selected_conf_obj = self.centralwidget.findChild(QLabel, c.lower() + "_conf_value")
            selected_conf_obj.setText("0.0")

    def update_inference_information(self, inference_info):
        self.II_preProcess_value.setText('{:.2f}'.format(inference_info["preprocess"]))
        self.II_inference_value.setText('{:.2f}'.format(inference_info["inference"]))
        self.II_postProcess_value.setText('{:.2f}'.format(inference_info["postprocess"]))

    def reset_obj_list(self, obj_list):
        for obj in obj_list:
            if obj.objectName()[-3:] == "led":
                obj.setStyleSheet(LED_OFF_CSS)
                obj.setEnabled(False)
            elif obj.objectName()[-5:] == "value":
                print(obj.objectName())
                obj.setText("0.0")

    def reset_gui_elements(self):
        print("reset gui elements")

        # Main Signal Group Box reset
        main_signal_objs = self.mainSignal_group.findChildren(QLabel)
        self.reset_obj_list(main_signal_objs)

        # Combination Signal Group Box reset
        combination_signal_objs = self.combinationSignal_group.findChildren(QLabel)
        self.reset_obj_list(combination_signal_objs)

        # Secondary Signal Group Box reset
        secondary_signal_objs = self.secondarySignals_group.findChildren(QLabel)
        self.reset_obj_list(secondary_signal_objs)

        # Inference Information Group Box reset
        inference_info_objs = self.inferenceInformation_group.findChildren(QLabel)
        self.reset_obj_list(inference_info_objs)

    def open_about_page(self):
        print("About Page")
        self.about_page_win = About_Page_Window()
        self.about_page_win.show()